import Head from 'next/head';
import { getCryptoEntryDataBySlug, getAllCryptoEntrySlugs } from '../../requests/crypto-entry';

export async function getStaticPaths() {
  const slugs = await getAllCryptoEntrySlugs();
  const paths = [];

  slugs.allCryptoEntries.map(entry => paths.push(`/cryptos/${entry.slug}`))

  return {
    paths,
    fallback: false
  };
}

export async function getStaticProps({ params }) {
  const data = await getCryptoEntryDataBySlug(params.slug);

  return {
    props: { data }
  }
}

export default function Crypto({data}) {
  const { cryptoEntry } = data;

  return (
    <div>
      <Head>
        <title>{ `Bert's Crypto | ${cryptoEntry.title}` }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
        <h1>{ cryptoEntry.title }</h1>

        <ul>
          { cryptoEntry.cryptos.map(({ id, cryptoHint, cryptoAnswer }) => (
            <li key={id}>{ cryptoHint } - { cryptoAnswer }</li>
          )) }
        </ul>
    </div>
  )
}
