import { useEffect } from 'react';
import { useStoreon } from 'storeon/react';
import Head from 'next/head';
import GridWrapper from '../../components/Modules/GridWrapper/GridWrapper';
import { getCryptoEntryDataBySlug, getAllCryptoEntrySlugs } from '../../requests/crypto-entry';
import { createGridFromData } from '../../utils/transformData';
import constants from '../../store/constants';

export async function getStaticPaths() {
  const slugs = await getAllCryptoEntrySlugs();
  const paths = [];

  slugs.allCryptoEntries.map(entry => paths.push(`/cryptos/${entry.slug}`))

  return {
    paths,
    fallback: false
  };
}

export async function getStaticProps({ params }) {
  const data = await getCryptoEntryDataBySlug(params.slug);
  const pageData = data?.cryptoEntry;

  const gridData = createGridFromData(data)

  return {
    props: { 
      crypto: pageData,
      gridData,
      slug: params.slug
    }
  }
}

export default function Crypto({ crypto, gridData }) {
  const { title, date } = crypto;
  const { dispatch } = useStoreon('grid');

  useEffect(() => {
    dispatch(constants.STORE.GRID.SET.DEFAULT, gridData);
  }, []);

  return (
    <div>
      <Head>
        <title>{ `Bert's Crypto | ${title}` }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
      <GridWrapper title={title} date={date} gridData={gridData} />
    </div>
  )
}
