import Head from 'next/head';

import { getHomepageData } from '../requests/main';
import CryptosList from '../components/Modules/CryptosList/CryptosList';

export async function getStaticProps() {
  const main = await getHomepageData();

  return {
    props: { main }
  }
}

export default function Home({main}) {
  const { homepage, allCryptoEntries } = main;
  return (
    <div className="l-wrapper">
      <Head>
        <title>Bert's Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <h1>{ homepage.title }</h1> */}
      <CryptosList list={allCryptoEntries} />
    </div>
  )
}
