import Head from 'next/head';
import Link from 'next/link';
import { getHomepageData } from '../requests/main';

export async function getStaticProps() {
  const data = await getHomepageData();

  return {
    props: { data }
  }
}

export default function Home({data}) {
  const { homepage, allCryptoEntries } = data;
  return (
    <div>
      <Head>
        <title>Bert's Crypto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{ homepage.title }</h1>
      <ul>
        { allCryptoEntries.map(({ id, title, slug }, index) => (
          index === 0 ? 
            <li key={id} >
              <Link href={`/cryptos/${slug}`}>
                { `${title} first` }
              </Link>
            </li>
            :
            <li key={id} >
              <Link href={`/cryptos/${slug}`}>
                { title }
              </Link>
            </li>
        )) }    
      </ul>
    </div>
  )
}
