import Head from 'next/head';
import { getSettingsPageData } from '../../requests/settings';

export async function getStaticProps() {
  const data = await getSettingsPageData();

  return {
    props: { data }
  }
}

export default function Settings({data}) {
const { settingsPage } = data;
console.log(data)
  return (
    <div>
      <Head>
        <title>Bert's Crypto | Settings</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>{ settingsPage.title }</h1>
    </div>
  )
}
